from django.db import models

# Create your models here.

class Item(models.Model):
    iclass = models.IntegerField()
    itype = models.IntegerField()
    subtype = models.IntegerField()
    itemftype = models.IntegerField()
    name = models.CharField(max_length=64)
    comment = models.CharField(max_length=256)
    use = models.CharField(max_length=256)
    name_eng = models.CharField(max_length=64)
    comment_eng = models.CharField(max_length=64)
    filename = models.CharField(max_length=64)
    bundlenum = models.IntegerField()
    invfilename = models.CharField(max_length=64)
    invbundlenum = models.IntegerField()
    cmtfilename = models.CharField(max_length=64)
    cmtbundlenum = models.IntegerField()
    equipfilename = models.CharField(max_length=64)
    pivotid = models.IntegerField()
    paletteid = models.IntegerField()
    options = models.CharField(max_length=128)
    hidehat = models.CharField(max_length=128)
    chrtypeflags = models.CharField(max_length=128)
    groundflags = models.IntegerField()
    systemflags = models.IntegerField()
    optionsex = models.CharField(max_length=128)
    weight = models.IntegerField()
    value = models.IntegerField()
    minlevel = models.IntegerField()
    effect = models.CharField(max_length=128)
    effectflags2 = models.IntegerField()
    selrange = models.IntegerField()
    life = models.IntegerField()
    depth = models.IntegerField()
    delay = models.FloatField()
    ap = models.IntegerField()
    hp = models.IntegerField()
    hpcon = models.IntegerField()
    mp = models.IntegerField()
    mpcon = models.IntegerField()
    money = models.IntegerField()
    applus = models.IntegerField()
    acplus = models.IntegerField()
    dxplus = models.IntegerField()
    maxmpplus = models.IntegerField()
    maplus = models.IntegerField()
    mdplus = models.IntegerField()
    maxwtplus = models.IntegerField()
    daplus = models.IntegerField()
    lkplus = models.IntegerField()
    maxhpplus = models.IntegerField()
    dpplus = models.IntegerField()
    hvplus = models.IntegerField()
    hprecoveryrate = models.FloatField()
    mprecoveryrate = models.FloatField()
    cardnum = models.IntegerField()
    cardgengrade = models.IntegerField()
    cardgenparam = models.FloatField()
    dailygencnt = models.IntegerField()
    partfilename = models.CharField(max_length=64)
    chrftypeflag = models.CharField(max_length=128)
    chrgender = models.IntegerField()
    existtype = models.IntegerField()
    ncash = models.IntegerField()
    newcm = models.IntegerField()
    famcm = models.IntegerField()
    summary = models.CharField(max_length=64)
    shopfilename = models.CharField(max_length=64)
    shopbundlenum = models.IntegerField()
    minstattype = models.IntegerField()
    minstatlv = models.IntegerField()
    refineindex = models.IntegerField()
    refinetype = models.IntegerField()
    compoundslot = models.IntegerField()
    setitemid = models.IntegerField()
    reformcount = models.IntegerField()
    groupid = models.IntegerField()

    def __unicode__(self):
        return self.name


class ItemAttribute(models.Model):
    item = models.ForeignKey(Item)
    fire = models.IntegerField()
    water = models.IntegerField()
    wind = models.IntegerField()
    earth = models.IntegerField()
    elec = models.IntegerField()
    light = models.IntegerField()
    dark = models.IntegerField()
    noprop = models.IntegerField()
    firer = models.IntegerField()
    waterr = models.IntegerField()
    windr = models.IntegerField()
    earthr = models.IntegerField()
    elecr = models.IntegerField()
    lightr = models.IntegerField()
    darkr = models.IntegerField()
    nopropr = models.IntegerField()
    physicalr = models.IntegerField()
    gunr = models.IntegerField()
    shadow = models.IntegerField()
    shadowr = models.IntegerField()

    def __unicode__(self):
        return unicode(self.item)
